name: first_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-ExtraBold.ttf

    - family: Helvetica
      fonts:
        - asset: assets/fonts/HelveticaNeueMedium.otf
        - asset: assets/fonts/HelveticaNeueLight.otf
          weight: 300

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/

flutter_launcher_icons:
  android: 'launcher_icon'
  ios: 'AppIcon'
  image_path: 'assets/icons/icon.png'
  min_sdk_android: 21
  remove_alpha_ios: true